export enum GaMatchType {
    MATCH_TYPE_UNSPECIFIED = 'MATCH_TYPE_UNSPECIFIED',
    EXACT = 'EXACT',
    BEGINS_WITH = 'BEGINS_WITH',
    ENDS_WITH = 'ENDS_WITH',
    CONTAINS = 'CONTAINS',
    FULL_REGEXP = 'FULL_REGEXP',
    PARTIAL_REGEXP = 'PARTIAL_REGEXP',
}

export type GaOperation =
    | 'OPERATION_UNSPECIFIED'
    | 'EQUAL'
    | 'LESS_THAN'
    | 'LESS_THAN_OR_EQUAL'
    | 'GREATER_THAN'
    | 'GREATER_THAN_OR_EQUAL';
